name: 'coverage'

on:
  pull_request_target:
    branches:
      - main
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest
    needs: pipeline
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2