name: Linter and Tests

on: 
  pull_request:
    branches:
      - develop

jobs:
  # pipeline:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.13.0
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Lint
  #       run: yarn lint
  #     - name: Build
  #       run: yarn build
  #     - name: Test
  #       run: yarn test-ci

  coverage:
    runs-on: ubuntu-latest
    needs: pipeline
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - name: Run Tests
        run: "yarn test-ci"
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          changes-only: true

