name: Linter and Tests

on: 
  pull_request:
    branches:
      - develop

jobs:
  Pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test-ci
      - name: Coverage
        uses: adRise/jest-cov-reporter@main
        with:
          branch-coverage-report-path: coverage/coverage-final.json
          base-coverage-report-path: coverage/coverage-final.json
          delta: 0.3
          accessToken: <GITHUB_TOKEN>
          fullCoverageDiff: true
          useSameComment: true