name: Linter and Tests

on: [pull_request]

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test-ci
      - name: Set code coverage commit status 📫
        run: npx -p check-code-coverage set-gh-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ensure coverage has not dropped 📈
        run: npx -p check-code-coverage set-gh-status --check-against-readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_SHA: ${{ github.event.after }}
